name: ZMK firmware build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install west
        run: pip install west

      - name: Init west workspace
        run: |
          west init -l config
          west update

      - name: Export Zephyr
        run: west zephyr-export

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y ninja-build gperf ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools xz-utils file make gcc g++ \
            libncurses-dev libsdl2-dev libmagic1

      - name: Build firmware
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble \
            -- -DSHIELD=simple_xiao \
               -DZMK_CONFIG=./config \
               -DZMK_EXTRA_MODULES=.

      - name: Upload UF2
        uses: actions/upload-artifact@v3
        with:
          name: zmk.uf2
          path: build/zephyr/zmk.uf2
